#!/bin/bash

if [[ $# -gt 0 ]] ; then
   Device=$1
else
   awk '/device/ { print $7 }' /tmp/ax25-config.tmp > /tmp/ax25-config-tmp
   read Device < /tmp/ax25-config-tmp

   if [[ -z "$Device" ]] ; then
      Device="ax0"
      echo "Set Device to default: $Device"
   fi
fi

echo "Using Device = $Device"

# For 1200 baud packet
T1_TIMEOUT="3000"
T2_TIMEOUT="1000"

# For 9600 baud packet
if [ -e "/etc/ax25/packet_9600baud" ] ; then
    T1_TIMEOUT="2000"
    T2_TIMEOUT="100"

fi

if [ -d /proc/sys/net/ax25/$Device ] ; then
 PARMDIR="/proc/sys/net/ax25/$Device"
# Parms for a USER Port
echo $T1_TIMEOUT    > $PARMDIR/t1_timeout	# (Frack) /1000 = ? Sec (1200 3000, 9600 2000)
echo $T2_TIMEOUT    > $PARMDIR/t2_timeout 	# (RESPtime) /1000 = ? sec (1200 1000, 9600 100)
echo 300000  > $PARMDIR/t3_timeout 		# (Check) /6000 = ? Min
echo 900000  > $PARMDIR/idle_timeout		# Idle Timer /6000 = ? min
echo 2       > $PARMDIR/standard_window_size	# Outstanding Frames
echo 6       > $PARMDIR/maximum_retry_count	# Max Retrys
echo 255     > $PARMDIR/maximum_packet_length	# Paclen
echo 0       > $PARMDIR/ax25_default_mode
echo 0       > $PARMDIR/ip_default_mode
echo 0       > $PARMDIR/backoff_type
echo 2       > $PARMDIR/connect_mode
#echo 180000 > $PARMDIR/dama_slave_timeout
echo 32      > $PARMDIR/extended_window_size
echo 0       > $PARMDIR/protocol

        ifconfig $Device netmask 255.255.255.255
else
        echo "** Error setting Device: $Device parms**"
fi
echo "ax25dev-parms finished"
exit 0
