#!/bin/bash
#
SBINPATH="/usr/local/sbin"

echo "ax25-downd start"
# Stop FPAC
#    /usr/local/sbin/myfpac.sh stop

# Stop Ax25 support
#  for PROC_NAME in beacon ax25d ax25ipd ax25rtd mheardd listen saxIgate
  for PROC_NAME in beacon ax25d ax25ipd ax25rtd mheardd saxIgate
    do
      PID=`/bin/pidof -x $PROC_NAME`
      if [ -n "$PID" ]; then
         kill -TERM $PID > /dev/null
         echo "$PROC_NAME - $PID "
         sleep 1
      fi
    done

# If netromd is running
  pidof netromd > /dev/null
  if [ $? -eq 0 ]; then

# Save NetRom routes
   $SBINPATH/nodesave -p $SBINPATH /var/ax25/nrsave && echo "N/R routes saved"

# Stop NetRom
    killall netromd > /dev/null
    echo "Netrom Stopped"
  else
    echo "Netrom daemon not running"
  fi

# Close sockets
echo "Detach Ax/Nr/Sp Devices"

ifconfig|grep AMPR > /tmp/ax25-config.tmp

i=0
iface=$(awk ' NR == '1' { print $1 }' /tmp/ax25-config.tmp)

while [ "$iface" != "" ] ; do
   let i=i+1
   iface=$(awk ' NR == '$i' { print $1 }' /tmp/ax25-config.tmp)
   if [ "$iface" != "" ] && [ "${iface:0:2}" == "nr" ] ; then
#      echo "select: $iface, iface: ${iface:0:2}"
      ifconfig "$iface" down
      echo " $iface down"
  fi
done

# Stop Kissattach
killall -KILL kissattach > /dev/null
# Empty Heard List
#cat /dev/null > /var/ax25/mheard/mheard.dat

# End of ax25-down
echo "ax25-downd finished"
exit 0
