#!/bin/bash
# version: 1.1
#
# Sets AX.25 device parameters
# Requires two arguments:
#  - arg1 = ax25 device name, either ax0 or ax1
#  - arg2 = ax25 device speed, either 1200 or 9600 baud

PORT_CFG_FILE="/etc/ax25/port.conf"

# Set defaults for 1200 baud packet
PORTSPEED="1200"
T1_TIMEOUT="3000"
T2_TIMEOUT="1000"

# Check command line arguments
if [[ $# -gt 0 ]] ; then
   Device=$1
else
   awk '/device/ { print $7 }' /tmp/ax25-config.tmp > /tmp/ax25-config-tmp
   read Device < /tmp/ax25-config-tmp

   if [[ -z "$Device" ]] ; then
       Device="ax0"
       echo "Set Device to default: $Device"
   fi

   if [[ $# -gt 1 ]] ; then
       PORTSPEED=$2
   fi
fi

# Get device parameters from config file
# Build baud rate section string
baudrate_parm="baud_$PORTSPEED"

if [ "$PORTSPEED" != "off" ] && [ ! -z "$PORTSPEED" ] ; then
    T1_TIMEOUT=$(sed -n "/\[$baudrate_parm\]/,/\[/p" $PORT_CFG_FILE | grep -i "^t1_timeout" | cut -f2 -d'=')
    T2_TIMEOUT=$(sed -n "/\[$baudrate_parm\]/,/\[/p" $PORT_CFG_FILE | grep -i "^t2_timeout" | cut -f2 -d'=')
fi

echo "Using Device = $Device"
if [ -d /proc/sys/net/ax25/$Device ] ; then
 PARMDIR="/proc/sys/net/ax25/$Device"
# Parms for a USER Port
echo $T1_TIMEOUT    > $PARMDIR/t1_timeout	# (Frack) /1000 = ? Sec (1200 3000, 9600 2000)
echo $T2_TIMEOUT    > $PARMDIR/t2_timeout 	# (RESPtime) /1000 = ? sec (1200 1000, 9600 100)
echo 300000  > $PARMDIR/t3_timeout 		# (Check) /6000 = ? Min
echo 900000  > $PARMDIR/idle_timeout		# Idle Timer /6000 = ? min
echo 2       > $PARMDIR/standard_window_size	# Outstanding Frames
echo 6       > $PARMDIR/maximum_retry_count	# Max Retrys
echo 255     > $PARMDIR/maximum_packet_length	# Paclen
echo 0       > $PARMDIR/ax25_default_mode
echo 0       > $PARMDIR/ip_default_mode
echo 0       > $PARMDIR/backoff_type
echo 2       > $PARMDIR/connect_mode
#echo 180000 > $PARMDIR/dama_slave_timeout
echo 32      > $PARMDIR/extended_window_size
echo 0       > $PARMDIR/protocol

        ifconfig $Device netmask 255.255.255.255
else
        echo "** Error setting Device: $Device parms**"
fi
echo "ax25dev-parms finished"
exit 0
