#!/bin/bash
#
# kern_cpy_local.sh
#
# Copy files to support udrc/udrx driver in a raspian linux source tree.
#
# DEBUG=1
# SHOW_DIFF=1

user="$(whoami)"
scriptname="`basename $0`"

kernver="4.15.rc8"

target_kern="/home/kernel/raspi_linux/raspi_$kernver"
compass_kern="/home/$user/dev/github/linux"

defconfig_cfg="CONFIG_SND_BCM2708_SOC_UDRC CONFIG_AD9832 CONFIG_ADF4360 CONFIG_CMX991 CONFIG_LCD_HX8357 CONFIG_AD525X_DPOT CONFIG_AD525X_DPOT_I2C CONFIG_SENSORS_IIO_HWMON CONFIG_SPI_DEBUG"

sound_soc_bcm_files="bcm2835-i2s.c Kconfig Makefile udrc.c"
sound_soc_codec_files="tlv320aic32x4.c tlv320aic32x4.h tlv320aic32x4-i2c.c tlv320aic32x4-spi.c"
boot_dts_overlay_files="udrc-boost-output-overlay.dts udrc-overlay.dts udrx-overlay.dts"
# this file is generated by compiler
snd_bcm2708_soc_incfile="udrc.h"
include_sound_incfile="tlv320aic32x4.h"

DIFF="diff -wBb"


# ===== function debugecho
function dbgecho { if [ ! -z "$DEBUG" ] ; then echo "$*"; fi }

# ===== function showdiff
function showdiff { if [ ! -z "$SHOW_DIFF" ] ; then $DIFF "$1" "$2"; fi }

# ===== function usage
function usage() {
   echo "Usage: $scriptname [-d][-h]" >&2
   echo "   -d no arg, diff udrc source files."
   echo "   -h no arg, display this message"
   echo
}

# ===== function diff_it

function diff_it() {
kpath="$1"
filelist="$2"

for filename in `echo ${filelist}` ; do
   file1="$compass_kern/$kpath/$filename"
   file2="$target_kern/$kpath/$filename"
   echo -n "=== diff $filename"
   if [ -e "$file2" ] ; then
      linecnt=$(diff -U 0 $file1  $file2 | grep ^@ | wc -l)
      echo ", $linecnt lines ==="
      showdiff $file1 $file2
   else
      echo " does not exist, copying ==="
      cp $file1 $file2
   fi
   ((filecnt++))
done


}

# ===== function diff_udrc_src

function diff_udrc_src() {
filecnt=0

kpath="arch/arm/configs"
fname="udr_defconfig"
file1="$compass_kern/$kpath/$fname"
file2="$target_kern/$kpath/$fname"
if [ ! -e "$file2" ] ; then
   echo "=== file: $fname does not exist, compare: bcm2709_defconfig"
   file2="$target_kern/$kpath/bcm2709_defconfig"
fi
echo -n "=== diff $fname "
if [ -e "$file2" ] ; then
   linecnt=$(diff -U 0 $file1  $file2 | grep ^@ | wc -l)
   echo ", $linecnt lines ==="
   showdiff $file1 $file2
else
   echo "does not exist ==="
fi
((filecnt++))

diff_it "sound/soc/bcm" "$sound_soc_bcm_files"
diff_it "sound/soc/codecs" "$sound_soc_codec_files"
diff_it "arch/arm/boot/dts/overlays" "$boot_dts_overlay_files"
diff_it "include/config/snd/bcm2708/soc" "$snd_bcm2708_soc_incfile"
diff_it "include/sound" "$include_sound_incfile"

echo
echo "Total files checked: $filecnt"

}

# ===== function check_target_kern

function check_target_kern() {
kpath="arch/arm/configs"
fname="udr_defconfig"
if [ -f "$compass_kern/$kpath/$fname" ] ; then
   echo "File: $target_kern/$kpath/$fname already exists"
else
   echo "File: $target_kern/$kpath/$fname does not exist"
fi
}

# ===== main

echo "Update a kernel source tree for UDRC"

# Be sure we're NOT running as root
if [[ $EUID == 0 ]] ; then
   echo "Don't be root"
   exit 1
fi

# Command line args are passed with a dash & single letter
#  See usage function
while [[ $# -gt 0 ]] ; do
key="$1"

case $key in
   -c)
      cpy_udrc_src
   ;;
   -C)
      check_target_kern
   ;;
   -d)
      diff_udrc_src
   ;;
   -h|--help|?)
      usage
      exit 0
   ;;
   *)
      # unknown option
      echo "Unknow option: $key"
      usage
      exit 1
   ;;
esac
shift # past argument or value
done


echo
echo "$scriptname: FINISHED"
